on:
  push:
  schedule:
    - cron: '0 8 * * *'
    - cron: '0 20 * * *'

name: transplantation

jobs:
  transplantation:
    name: "Incorporating the latest changes"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: ["master", "RELEASE_3_12"]
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}
          fetch-depth: 0
      - name: Transplant book contents
        uses: LTLA/TrojanBookBuilder@master
        with:
          book: Bioconductor/OrchestratingSingleCellAnalysis
          branch: ${{ matrix.branch }}
          name: OSCA
          biocViews: "ImmunoOncologyWorkflow, Workflow, SingleCellWorkflow"
      - name: Committing to master
        run: | 
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Incorporate latest changes from book." || true
          git push
      - name: Setting up the private key
        uses: webfactory/ssh-agent@v0.4.0
        with:
          ssh-private-key: ${{ secrets.BIOC_PRIVATE_KEY }}
      - name: Pushing to Bioconductor
        run : |
          ssh-keyscan -t rsa git.bioconductor.org >> /home/runner/.ssh/known_hosts
          git remote add upstream git@git.bioconductor.org:packages/OSCA
          git pull upstream ${{ matrix.branch }}        
          git push upstream ${{ matrix.branch }}
